### ISSUE TITLE
Write documentation/ update Readme about the project

### ISSUE THREAD

**Issue by KritikaSh2** [KritikaSh2/AnimeTracker#1]
Few points for the content:
- Built using flutter and firebase
- Used Jikan Api (provide link) for the anime data
- Features like save to favourites, watchlist status - watched, watching, want to watch
- Related and recommendations on the detail page of each anime
- Categories include currently airing, upcoming, top of all time, movies
- Change profile name and profile photo

**Comment by JoelChandanshiv** [comment]
HI @KritikaSh2 i want to work on this issue . Can u please assign me this issue .

**Comment by KritikaSh2** [comment]
Sure

**Comment by KritikaSh2** [comment]
@JoelChandanshiv please confirm if you are working on this.

**Comment by Sankalp-sa** [comment]
Hii, @KritikaSh2 I have created the pull request for this issue could you please check and let me know If some changes are needed. https://github.com/KritikaSh2/AnimeTracker/pull/4
